name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python tests
        run: pytest -q
      - name: Build & run C++ tests (ctest)
        run: |
          cmake -S . -B build
          cmake --build build -j
          ctest --test-dir build -q
